sudo: false

language: python

python:
  - 3.5

jobs:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install pytest

script:
   - tox -e $TOXENV

after_success:
  - codecov
